apiVersion: apps/v1
kind: Deployment
metadata:
  name: onekingdom-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onekingdom-frontend
  template:
    metadata:
      labels:
        app: onekingdom-frontend
    spec:
      containers:
      - name: onekingdom-frontend
        image: ghcr.io/onekingdom/onekingdom-website:046a90301e5269cd7e493833e08bfab595306c6f
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: onekingdom-frontend