apiVersion: apps/v1
kind: Deployment
metadata:
  name: onekingdom-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onekingdom-frontend
  template:
    metadata:
      labels:
        app: onekingdom-frontend
    spec:
      containers:
      - name: onekingdom-frontend
        image: ghcr.io/onekingdom/onekingdom-website:cc9f9c942f792a590ee7d228f20e841f1a1ef2ee
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: onekingdom-frontend